---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - export DOCKER_HOST=unix:///var/run/host.sock
  - docker login -u 'robot$drone' -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
  - docker build --build-arg SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY -t harbor.dsrd.libraries.psu.edu/library/etda-workflow:$DRONE_BUILD_NUMBER . 
  - docker tag harbor.dsrd.libraries.psu.edu/library/etda-workflow:$DRONE_BUILD_NUMBER harbor.dsrd.libraries.psu.edu/library/etda-workflow:ci
  - docker push harbor.dsrd.libraries.psu.edu/library/etda-workflow:$DRONE_BUILD_NUMBER 
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

- name: prepare
  image: harbor.dsrd.libraries.psu.edu/library/etda-workflow:ci
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_HOST: mariadb
    REDIS_HOST: redis
  depends_on:
  - build
  commands:
    - cd /etda_workflow
    - export RAILS_ENV=test
    - unset CI
    - export QT_QPA_PLATFORM=offscreen
    # - bundle install --with development test
    - bundle exec rake db:create
    - bundle exec rake db:test:load
    - bundle exec rake db:migrate

- name: test-controllers
  image: harbor.dsrd.libraries.psu.edu/library/etda-workflow:ci
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_HOST: mariadb
    REDIS_HOST: redis
  depends_on:
  - prepare
  commands:
    - cd /etda_workflow
    - unset CI
    - export QT_QPA_PLATFORM=offscreen
    - bundle exec rake spec:controllers

- name: test-models
  image: harbor.dsrd.libraries.psu.edu/library/etda-workflow:ci
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_HOST: mariadb
    REDIS_HOST: redis
  depends_on:
  - prepare
  commands:
    - cd /etda_workflow
    - unset CI
    - export QT_QPA_PLATFORM=offscreen
    - bundle exec rake spec:models

- name: tag
  image: alpine/git
  depends_on:
    - prepare
    - test-controllers
    - test-models
  commands:
  - cd k8s/chart
  - 'sed -i "/^image:/,/*[^:]*:/s/tag:.*/tag: $DRONE_BUILD_NUMBER/g" values-$DRONE_BRANCH.yaml'
  - git config user.email "drone@drone2test.vmhost.psu.edu"
  - git config user.name "DroneCI"
  - git add values-$DRONE_BRANCH.yaml
  - git commit -m "[skip ci] adds $DRONE_BUILD_NUMBER"
  - git push -u origin $DRONE_BRANCH


services:
- name: mariadb
  image: mariadb:10.4.5
  environment:
    MYSQL_ROOT_PASSWORD: root
  
- name: redis
  image: redis


# - name: notify
#   image: drillster/drone-email
#   settings:
#     host: smtp.psu.edu
#     from: drone@drone-test.dsrd.libraries.psu.edu
#   when:
#    status: [ changed, success, failure ]
  
volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock
