inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Rails:
  Enabled: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'config/deploy/**/*'
    - 'spec/lib/tasks/*'
    - 'spec/routing/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'webpack.config.js'

Metrics/LineLength:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
  - app/models/submission.rb
  - app/models/author.rb
  - app/models/mock_university_directory.rb
  - app/models/legacy/importer.rb
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/controllers/author/submissions_controller.rb
  - app/presenters/submission_view.rb


Metrics/CyclomaticComplexity:
  Exclude:
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/presenters/admin/submission_form_view.rb

Metrics/PerceivedComplexity:
  Exclude:
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/presenters/admin/submission_form_view.rb

Layout/MultilineBlockLayout:
  Exclude:

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassVars:
  Exclude:
   - 'spec/support/authentication.rb'

Naming/VariableName:
  Exclude:

Style/GlobalVars:
  Exclude:
    - 'node_modules/node-sass/src/libsass/extconf.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/deploy.rb'
    - 'spec/component/models/solr_data_import_service_spec.rb'

Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'config/application.rb'

Naming/PredicateName:
  Exclude:
    - 'app/validators/virus_free_validator.rb'

Lint/HandleExceptions:
  Exclude:
    - 'spec/component/models/legacy/importers/degree_importer_spec.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'lib/devise/strategies/webaccess_authenticatable.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Lint/UnreachableCode:
  Exclude:
    - 'app/presenters/admin/submission_form_view.rb'

Rails/Date:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/deploy.rb'
    - 'config/qa-grad.rb'
    - 'config/qa-honors.rb'

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/admin/manage_degrees_spec.rb'
    - 'spec/integration/admin/manage_programs_spec.rb'
    - 'spec/integration/admin/manage_submissions_spec.rb'
    - 'spec/integration/admin/manage_authors_spec.rb'
    - 'spec/lib/tasks/confidential_rake_spec.rb'
    - 'spec/lib/tasks/legacy/legacy_importer_spec.rb'

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
   - 'spec/lib/tasks/legacy/legacy_importer_spec.rb'
   - 'spec/integration/admin/manage_authors_spec.rb'

RSpec/PredicateMatcher:
  Exclude:
   - 'spec/lib/tasks/legacy/legacy_importer_spec.rb'
   - 'spec/lib/tasks/confidential_rake_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'config/deploy.rb'

Naming/FileName:
  Exclude:
    - 'config/qa-grad.rb'
    - 'config/qa-honors.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/tasks/dev.rake'

Lint/UselessAssignment:
  Exclude:
    - 'app/views/admin/**/*.rabl'
    #- 'app/views/admin/degrees/index.json.rabl'
    #- 'app/views/admin/programs/index.json.rabl'
    - 'lib/tasks/confidential.rake'
    - 'spec/models/lion_path/academic_plan_spec.rb'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/update'
    - 'bin/yarn'
    - 'db/schema.rb'

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'app/views/admin/submissions/table_bodies/_format_review_submitted.json.jbuilder'

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false




