inherit_from: .rubocop_todo.yml

require: [rubocop-rspec, rubocop-rails]

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'config/deploy/**/*'
    - 'spec/routing/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'webpack.config.js'
    - 'spec/lib/**/*'
    - 'spec/support/ldap_lookup.rb'
    - 'lib/tasks/**/*'
    - 'Gemfile*'
    - 'Capfile'
    - 'spec/*_helper.rb'
    - 'lib/devise/**/*'
    - 'app/models/submission_status_giver.rb'
    - 'spec/models/submission_status_giver_spec.rb'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/ClassLength:
  Exclude:
  - app/models/submission.rb
  - app/models/author.rb
  - app/models/mock_university_directory.rb
  - app/models/legacy/importer.rb
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/presenters/author/submission_view.rb
  - app/presenters/admin/submission_form_view.rb
  - app/models/legacy/file_importer.rb
  - app/models/ldap_result.rb
  - app/services/submission_release_service.rb
  - app/models/submission_status.rb
  - app/mailers/workflow_mailer.rb
  - app/controllers/approver/approvers_controller.rb
  - app/controllers/author/submissions_controller.rb
  - app/models/committee_member.rb

Metrics/CyclomaticComplexity:
  Exclude:
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/presenters/admin/submission_form_view.rb
  - app/services/submission_release_service.rb
  - app/models/export_csv.rb
  - app/models/mock_university_directory.rb
  - app/helpers/application_helper.rb
  - app/models/submission.rb
  - app/presenters/author/submission_view.rb
  - app/controllers/author/committee_members_controller.rb
  - app/presenters/author/committee_member_view.rb
  - app/models/committee_member.rb

Metrics/PerceivedComplexity:
  Exclude:
  - app/controllers/admin/submissions_controller.rb
  - app/presenters/admin/submissions_dashboard_view.rb
  - app/presenters/admin/submissions_index_view.rb
  - app/presenters/admin/submission_form_view.rb
  - app/models/export_csv.rb
  - app/helpers/application_helper.rb
  - app/services/submission_release_service.rb
  - app/models/submission.rb
  - app/presenters/author/submission_view.rb
  - app/controllers/author/committee_members_controller.rb
  - app/presenters/author/committee_member_view.rb
  - app/models/committee_member.rb

Layout/MultilineBlockLayout:
  Exclude:

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods


Naming/VariableName:
  Exclude:

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Exclude:
  - 'app/controllers/admin/submissions_controller.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassVars:
  Exclude:
   - 'spec/support/authentication.rb'

Style/GlobalVars:
  Exclude:
    - 'node_modules/node-sass/src/libsass/extconf.rb'

Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/services/solr_data_import_service_spec.rb'

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/services/solr_data_import_service_spec.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'config/application.rb'

Naming/PredicateName:
  Exclude:
    - 'app/validators/virus_free_validator.rb'

Lint/SuppressedException:
  Exclude:
    - 'spec/component/models/legacy/importers/degree_importer_spec.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Lint/UnreachableCode:
  Exclude:
    - 'app/presenters/admin/submission_form_view.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/admin/manage_degrees_spec.rb'
    - 'spec/integration/admin/manage_programs_spec.rb'
    - 'spec/integration/admin/manage_submissions_spec.rb'
    - 'spec/integration/admin/manage_authors_spec.rb'
    - 'spec/lib/tasks/confidential_rake_spec.rb'
    - 'spec/lib/tasks/legacy/legacy_importer_spec.rb'
    - 'spec/integration/admin/submissions/unrelease_spec.rb'
    - 'spec/integration/admin/submissions/*_spec.rb'
    - 'spec/lib/*.*'
    - 'spec/integration/**/*'

RSpec/MultipleDescribes:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/format_review_files_spec.rb'
    - 'spec/controllers/author_controller_spec.rb'
    - 'spec/controllers/admin_controller_spec.rb'
    - 'spec/controllers/approver_controller_spec.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/PredicateMatcher:
  Exclude:
   - 'spec/lib/tasks/legacy/legacy_importer_spec.rb'
   - 'spec/lib/tasks/confidential_rake_spec.rb'
   - 'spec/models/admin_ability_spec.rb'
   - 'spec/models/author_ability_spec.rb'
   - 'spec/models/approver_ability_spec.rb'

Naming/FileName:
  Exclude:
    - 'config/qa-grad.rb'
    - 'config/qa-honors.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/tasks/dev.rake'

Lint/UselessAssignment:
  Exclude:
    - 'app/views/admin/**/*.rabl'
    #- 'app/views/admin/degrees/index.json.rabl'
    #- 'app/views/admin/programs/index.json.rabl'
    - 'spec/lib/tasks/confidential.rake'
    - 'app/models/legacy/importer.rb'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'app/views/admin/submissions/table_bodies/_format_review_submitted.json.jbuilder'

Style/NestedParenthesizedCalls:
  Exclude:
   - 'spec/models/admin_ability_spec.rb'
   - 'spec/models/author_ability_spec.rb'


Style/BlockDelimiters:
  Exclude:
   - 'config/deploy.rb'

Style/EmptyMethod:
  Enabled: false


RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExpectActual:
  Exclude:
    - 'spec/controllers/**/**'

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/MultipleComparison:
  Enabled: false
