require: rubocop-rspec

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'config/deploy/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
  - app/models/submission.rb

Metrics/CyclomaticComplexity:
  Exclude:

Metrics/PerceivedComplexity:
  Exclude:

Style/MultilineBlockLayout:
  Exclude:

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassVars:
  Exclude:

Style/VariableName:
  Exclude:

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/deploy.rb'
    - 'spec/component/models/solr_data_import_service_spec.rb'

Style/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Style/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Style/AccessorMethodName:
  Exclude:
    - 'config/application.rb'

Style/PredicateName:
  Exclude:
    - 'app/validators/virus_free_validator.rb'

Lint/HandleExceptions:
  Exclude:
    - 'spec/component/models/legacy/importers/degree_importer_spec.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'lib/devise/strategies/webaccess_authenticatable.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails/Date:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/deploy.rb'
    - 'config/qa-grad.rb'
    - 'config/qa-honors.rb'

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:

RSpec/MultipleDescribes:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'config/deploy.rb'

Style/FileName:
  Exclude:
    - 'config/qa-grad.rb'
    - 'config/qa-honors.rb'

