language: ruby
# cache: bundler
bundler_args: "--without development debug"
# sudo: required
#rvm:
#- 2.4.3
jdk:
- oraclejdk12
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JS=true
  - unset TZ
  - export TZ='Eastern Time (US & Canada)'
before_install:
- "gem --version"
- "gem update --system"
- "gem --version"
- 'gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"'
- export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
- if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi
- if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi
- if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi
- phantomjs --version
before_script:
- 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1'
- 'export PATH=$HOME/.yarn/bin:$PATH'
- "cp config/database.yml.travis config/database.yml"
- "cp config/devise.yml.travis config/devise.yml"
- "cp config/secrets.yml.travis config/secrets.yml"
- "cp config/lion_path.yml.travis config/lion_path.yml"
- "cp config/redis.yml.travis config/redis.yml"
- "cp config/sidekiq.yml.travis config/sidekiq.yml"
- redis-cli info
# cache:
#  yarn: true
#  directories: node_modules
script:
- "export PARTNER=graduate"
- "bundle exec rake db:create"
- "bundle exec rake db:test:load"
- "bundle exec rake db:migrate RAILS_ENV=test"
- "yarn install"
- "echo $(date)"
- "bundle exec rake ci"
services:
- mysql
- redis-server
addons:
  mariadb: '10.2'
notifications:
  email:
    recipients:
    - ajk5603@psu.edu
    - amg32@psu.edu
    on_success: change
    on_failure: always
  irc:
    channels:
    template:
dd:
  secure: I3Oa3/YtT0UCRM6gIU7z9ab15bn1DVC9EC9b2zXfCkq02aPbTgkyMYZCBgwEcuIsGcf8Yydl/7r/vZmqyEoMHbqjYB3m6Ct3jHaFpVLor7movIg4mr2lZpRJ0NLzG26b7ICG5AmNlBx+fZGRv/+cjNqVd9AdYCni1Rd3iYjxlBOjgNnCpFNLjVDLcfRZlFzFe7zq4Cz2whF0qgC4NQQNMH0jmLixfOP+JAF+p62aJwKe+qsivpyYLX0FK8W9PMdOGodeBvJY+OOqAk+cAl7BVhoP4QhXVOHvRWvtL1CL/vYITeR+RvckfNUScgGQU3XhkoJ2hzYHafHF5SP3zjecDc7kLnkpe+n9/FLDGp8PDaZStZWpxFzWE4IIMUbgYd3KeXV3bsYktUNWG6R/hnw6Z1JlvLs+anefPnQDBuRU4ygraGtUgXqRSKuaPQODJDA1s5iqVBcXnvRT4oEDDG6NUf8LE1MULUvw+hfCKHVHrhlg9VF/Iee57owwUS0KP1FotvKU2KsV4/yqi54dl7aZQ2MbzrqmRKOSyOG6gxgZ/yXMzAAmy5h3NeIrhhoDz/qmrayN5XaLowvVZsBA7mbmS1GKt+4Qg+Hfoqzc259iP/Iuo6PAxf7SZJ1hl3a4R+zlyacCA4o/wa0UfKG7HN/kNdWWRoCC3kP34Ev5HAdtCjs=
