require 'spec_helper'
require 'support/rails'
require 'support/database_cleaner'
# require 'support/committee_factory'
# require 'support/keyword_factory'
# require 'support/factories'
require 'support/fixture'
require 'support/i18n'
# require 'support/mail'
require 'support/ldap_lookup'
# require 'support/matchers/have_db_foreign_key'
# require 'support/partner'
require 'rails_helper'
