# frozen_string_literal: true

require 'spec_helper'
require 'support/rails'
require 'support/fixture'
require 'support/poltergeist'
require 'support/poltergeist_helpers'
require 'support/database_cleaner'
# require 'support/factories'
# require 'support/mail'
require 'support/i18n'
require 'support/capybara'
# require 'support/committee_factory'
# require 'support/basic_auth'
require 'support/authentication'
require 'support/ldap_lookup'
require 'support/capybara_email'
