default: &default
  username: <%= ENV.fetch("LIONPATH_USERNAME", "") %>
  password: <%= ENV.fetch("LIONPATH_PASSWORD", "") %>
  honors:
    lion_path_outbound: <%= ENV.fetch("HONORS_LIONPATH_OUTBOUND", "false") %>
    lion_path_inbound: <%= ENV.fetch("HONORS_LIONPATH_OUTBOUND", "false") %>
  milsch:
    lion_path_outbound: <%= ENV.fetch("MILSCH_LIONPATH_OUTBOUND", false) %>
    lion_path_inbound: <%= ENV.fetch("MILSCH_LIONPATH_OUTBOUND", false) %>
  graduate:
    lion_path_outbound: <%= ENV.fetch("GRADUATE_LIONPATH_OUTBOUND", false) %>
    lion_path_inbound: <%= ENV.fetch("GRADUATE_LIONPATH_OUTBOUND", false) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default