production:
  :usersname: user
  :password: password
  graduate:
    :lion_path_outbound: false
    :lion_path_inbound: false 
  honors:
    :lion_path_outbound: false
    :lion_path_inbound: false
  milsch:
    :lion_path_outbound: false
    :lion_path_ibnound: false

#  qna_url:  'https://qna.lionpath.psu.edu/PSIGW/RESTListeningConnector/PSFT_HR'
#  tst_url:  'https://etdeht:XXXXXX@test-ib1.lionpath.psu.edu/PSIGW/RESTListeningConnector/PSFT_HR'

development:
  :username: user
  :password: password
  graduate:
    :lion_path_outbound: false
    :lion_path_inbound: false
  honors:
    :lion_path_outbound: false
    :lion_path_inbound: false
  milsch:
    :lion_path_outbound: false
    :lion_path_inbound: false

test:
  :username: user
  :password: password 
  graduate:
    :lion_path_outbound: false
    :lion_path_inbound: false
  honors:
    :lion_path_outbound: false
    :lion_path_inbound: false
  milsch:
    :lion_path_outbound: false
    :lion_path_inbound: false

