default: &default
  host: <%= ENV.fetch("REDIS_HOST") { "localhost" } %>
  port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
  timeout: <%= ENV.fetch("REDIS_TIMEOUT") { 1000 } %>
<% if ENV.fetch("REDIS_PASSWORD", nil) %>
  password: <%= ENV.fetch("REDIS_PASSWORD", "password") %>
<% end %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
