#Replace 'put-your-secret-token-here' with a unique, private token.  Generate a token by running `rails secret`.

development:
  secret_key_base: put-your-secret-token-here

test:
  secret_key_base: put-your-secret-token-here

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "super-secret-token" } %>
  email_indicator: <%= ENV.fetch("EMAIL_INDICATOR") { ":test" }  %>