#Replace 'put-your-secret-token-here' with a unique, private token.  Generate a token by running `rails secret`.

development:
  secret_key_base: put-your-secret-token-here
  webaccess:
    vservice:    'http://etda_workflow.localhost:3000'
    path:     'devpath'
    google_analytics_tracking_id: 'UA-bogusanalytics-1'

test:
  secret_key_base: put-your-secret-token-here
  webaccess:
    vservice:    'http://etda_workflow.localhost:3000'
    path:     'testpath'
    google_analytics_tracking_id:   'UA-bogusanalytics-1'

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  email_indicator: <%= ENV.fetch("EMAIL_INDICATOR") { ":test" }  %>