dependencies:
- name: redis
  version: 0.1.6
  repository: https://harbor.dsrd.libraries.psu.edu/chartrepo/public
  condition: redis.enabled
- name: mariadb
  version: 0.0.7
  repository: https://harbor.dsrd.libraries.psu.edu/chartrepo/public
  condition: mariadb.enabled